# version: "3.9"
services:
  # ===== Rails (API) =====
  backend:
    # Dockerfileの場所 (./back-end ディレクトリを指定)
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: rails-backend
    # ポート:ホスト側:コンテナ側
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
    environment:
      RAILS_ENV: development
    # depends_on: []
    command: ["bundle", "exec", "bin/rails", "server", "-b", "0.0.0.0", "-p", "3001"]
